export const actionType = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    SET_ERROR: 'SET_ERROR',
    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
    PURCHASE_INIT: 'PURCHASE_INIT',
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    AUTHORISATION_START: 'AUTHORISATION_START',
    AUTHORISATION_FAIL: 'AUTHORISATION_FAIL',
    AUTHORISATION_SUCCESS: 'AUTHORISATION_SUCCESS',
    AUTHORISATION_LOGOUT: 'AUTHORISATION_LOGOUT'
}

export const actionPayload = {
    
}